## single dimension NumPy Array


In [76]:
# !pip install numpy

In [8]:
# we cannot perform in different data types
import numpy as np
n1 = np.array([10,20,30,40])
n1

array([10, 20, 30, 40])

In [7]:
type(n1)

numpy.ndarray

## multidimensional numpy array

In [10]:
import numpy as np
n2=np.array([[10,20,30],[10,80,90],[30,50,80]])
print(n2)

[[10 20 30]
 [10 80 90]
 [30 50 80]]


In [11]:
n2.shape

(3, 3)

## initilize NumPy array with zeros

In [12]:
n3 = np.zeros((9,9))
n3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## initilization a array of matrix with full then

In [14]:
n4 = np.full((6,6),8)
n4

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

## initilization of NumPy with a range

In [16]:
n5 = np.arange(10,20)
n5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

## initilization of NumPy array with the skip numbers

In [19]:
n6 = np.arange(1,10,2)
n6

array([1, 3, 5, 7, 9])

## initilizaton Numpy array with the random numbers

In [24]:
# OTP generation
n7 = np.random.randint(100,1000,10)
n7

array([781, 995, 466, 317, 589, 168, 395, 836, 765, 804])

## initilization the array shape changes in fraction of seconds

In [25]:
n8 = np.array([[10,20,30],[10,80,90],[30,20,80],[30,60,90]])
n8

array([[10, 20, 30],
       [10, 80, 90],
       [30, 20, 80],
       [30, 60, 90]])

In [26]:
n8.shape

(4, 3)

In [28]:
n8.shape=(3,4)
n8

array([[10, 20, 30, 10],
       [80, 90, 30, 20],
       [80, 30, 60, 90]])

## joining numpy array .

In [33]:
a = np.array([10,20,30,40,50,60,70,80,90,15])
b = np.array([11,22,33,44,55,66,77,88,99,96])
np.vstack((a,b))  #joining the numpy as a vertical section

array([[10, 20, 30, 40, 50, 60, 70, 80, 90, 15],
       [11, 22, 33, 44, 55, 66, 77, 88, 99, 96]])

In [34]:
np.hstack((a,b)) #joining the numpy as a horizontal section

array([10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 11, 22, 33, 44, 55, 66, 77,
       88, 99, 96])

In [35]:
np.column_stack((a,b)) #joining the numpy as a vertical column section

array([[10, 11],
       [20, 22],
       [30, 33],
       [40, 44],
       [50, 55],
       [60, 66],
       [70, 77],
       [80, 88],
       [90, 99],
       [15, 96]])

## numpy intersection and differrences

In [36]:
x = np.array([10,20,30,40,50,60])
y = np.array([30,100,50,23,56,79])
np.intersect1d(x,y)

array([30, 50])

In [37]:
np.setdiff1d(x,y)

array([10, 20, 40, 60])

In [38]:
np.setdiff1d(y,x)

array([ 23,  56,  79, 100])

## addition of numpy arrays

In [39]:
t=np.array([10,20])
s=np.array([30,40])
np.sum([t,s])

100

In [40]:
np.sum([t,s],axis=0)

array([40, 60])

In [41]:
np.sum([t,s],axis=1)

array([30, 70])

## numpy array mathematics

In [42]:
p=np.array([10,20,30])
p+1

array([11, 21, 31])

In [43]:
p-1

array([ 9, 19, 29])

In [44]:
p/2

array([ 5., 10., 15.])

In [45]:
p%2

array([0, 0, 0], dtype=int32)

In [47]:
p*2

array([20, 40, 60])

## NumPy maths functions

In [48]:
nn=np.array([10,20,30,60])
np.mean(nn)

30.0

In [49]:
np.median(nn)

25.0

In [50]:
np.std(nn)

18.708286933869708

In [51]:
np.var(nn)

350.0

In [52]:
np.min(nn)

10

In [53]:
np.max(nn)

60

In [56]:
np.average(nn)

30.0

In [59]:
np.percentile(nn,50)

25.0

In [63]:
np.quantile(nn,0.25)

17.5

In [65]:
np.cov(nn)  #coefficient of varaiance

array(466.66666667)

In [72]:
# !pip install scipy

In [70]:
from scipy import stats

In [71]:
stats.mode(nn)

ModeResult(mode=10, count=1)

## saving and loading NumPy array

In [74]:
n11=np.array([10,20,30,40,50])
np.save('my_name',n11) #saving the NumPy array

In [75]:
np.load('my_name.npy')

array([10, 20, 30, 40, 50])

In [77]:
pip install graphviz

Note: you may need to restart the kernel to use updated packages.


In [78]:
!pip install dask

In [79]:
!pip install pandas

In [80]:
!pip install pyspark

     ---------------------------------------- 0.0/434.1 MB ? eta -:--:--
     ---------------------------------------- 0.0/434.1 MB ? eta -:--:--
     ---------------------------------------- 0.5/434.1 MB 2.1 MB/s eta 0:03:27
     ---------------------------------------- 0.8/434.1 MB 2.1 MB/s eta 0:03:27
     ---------------------------------------- 1.3/434.1 MB 1.8 MB/s eta 0:03:59
     ---------------------------------------- 1.6/434.1 MB 2.2 MB/s eta 0:03:21
     ---------------------------------------- 2.1/434.1 MB 1.9 MB/s eta 0:03:49
     ---------------------------------------- 2.4/434.1 MB 1.9 MB/s eta 0:03:46
     ---------------------------------------- 2.9/434.1 MB 1.9 MB/s eta 0:03:52
     ---------------------------------------- 3.1/434.1 MB 1.9 MB/s eta 0:03:49
     ---------------------------------------- 3.7/434.1 MB 1.9 MB/s eta 0:03:47
     ---------------------------------------- 4.2/434.1 MB 1.9 MB/s eta 0:03:43
     ---------------------------------------- 4.5/434.

In [81]:
pip install seaborn

Note: you may need to restart the kernel to use updated packages.


In [82]:
!pip install scikit-learn