## 4.Uniform Samples

In [3]:
! pip install numpy


In [5]:
import numpy as np

In [7]:
np.random.uniform(5,10,size=4)

array([8.61970924, 5.96268062, 9.00262106, 5.95808001])

## log space

In [9]:
#np.logspace(start,stop,num=50,endpoint=True,base=10.0)

## identity

In [10]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Digitize

In [11]:
a = np.array([-0.9,0.5,0.9,1,1.2,1.2,1.4,3.6,4.7,5.3])
bins = np.array([0,1,2,3])
np.digitize(a,bins)

array([0, 1, 1, 2, 2, 2, 2, 4, 4, 4], dtype=int64)

## expand dimensions

In [13]:
arr = np.array([8,14,1,8,11,4,9,4,13,13,11])
np.expand_dims(arr,axis=0)

array([[ 8, 14,  1,  8, 11,  4,  9,  4, 13, 13, 11]])

In [14]:
np.expand_dims(arr,axis=1)

array([[ 8],
       [14],
       [ 1],
       [ 8],
       [11],
       [ 4],
       [ 9],
       [ 4],
       [13],
       [13],
       [11]])

## squeeze

In [16]:
arr = np.array([8,14,1,8,11,4,9,4,13,13,11])
np.squeeze(arr)

array([ 8, 14,  1,  8, 11,  4,  9,  4, 13, 13, 11])

## count non-zero

In [17]:
a = np.array([0,0,1,1,1,0])
np.count_nonzero(a)

3

In [18]:
b = (len(a))
print(abs(b-np.count_nonzero(a)))

3


## sort

In [19]:
arr = np.array([2,3,1,7,4,5])
np.sort(arr)

array([1, 2, 3, 4, 5, 7])

## abs

In [21]:
A = np.array([[1,-3,4],[-2,-4,3]])
np.abs(A)

array([[1, 3, 4],
       [2, 4, 3]])

## Round

In [22]:
a = np.random.random(size=(3,4))
a

array([[0.74893291, 0.1349571 , 0.02035566, 0.35514894],
       [0.09223664, 0.98779732, 0.45045877, 0.34051197],
       [0.64085935, 0.02399415, 0.70926379, 0.28319109]])

In [23]:
np.round(a,decimals=0)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 1., 0.]])

In [24]:
np.round(a,decimals=1)

array([[0.7, 0.1, 0. , 0.4],
       [0.1, 1. , 0.5, 0.3],
       [0.6, 0. , 0.7, 0.3]])

## clip

In [25]:
arr = np.array([0,1,-3,-4,5,6,7,2,3])
arr.clip(0,5)

array([0, 1, 0, 0, 5, 5, 5, 2, 3])

In [26]:
arr.clip(0,3)

array([0, 1, 0, 0, 3, 3, 3, 2, 3])

In [27]:
arr.clip(3,5)

array([3, 3, 3, 3, 5, 5, 5, 3, 3])

## Copy to

In [30]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print("before arr1",arr1)
print("before arr2",arr2)
np.copyto(arr1,arr2)
print("after arr1",arr1)
print("after arr1",arr1)

before arr1 [1 2 3]
before arr2 [4 5 6]
after arr1 [4 5 6]
after arr1 [4 5 6]


In [31]:
## 

In [42]:
a = ([[1,2,3],[4,5,6],[7,8,9]])
b = ([[3,1,3],[1,5,1],[7,1,9]])


In [43]:
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [44]:
b

[[3, 1, 3], [1, 5, 1], [7, 1, 9]]

In [55]:
# transpose
np.einsum('ij->ji',a)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [45]:
np.einsum('ji',a)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [49]:
# SUM OF DIAGONAL
np.einsum('ii',a)

15

In [48]:
# matix multiplication
np.einsum('ij,jk',a,b)

array([[ 26,  14,  32],
       [ 59,  35,  71],
       [ 92,  56, 110]])

In [52]:
c=np.array([[3,4],[5,6]])
c

array([[3, 4],
       [5, 6]])

In [54]:
# determinant
np.linalg.det(c)

-2.0000000000000004

In [58]:
int(np.linalg.det(c))

-2

In [59]:
np.linalg.inv(c)

array([[-3. ,  2. ],
       [ 2.5, -1.5]])

In [60]:
# Basic summation
a = np.array([1,2,3])
print(np.einsum('i->',a))

6


In [68]:
# element wise multiplication and summation
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.einsum('i,i->',a,b)) # dot produtc

32


In [69]:
# outer product ie; i * j transpose
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.einsum('i,j->ij',a,b))

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [75]:
# matrix transposition
A = np.array([[1,2,3],[4,5,6]])
print(np.einsum('ij->ji',A)) #transpose matrix


[[1 4]
 [2 5]
 [3 6]]


In [76]:
# matrix-vector multiplication
A = np.array([[1,2],[3,4],[5,6]])
x = np.array([7,8])
print(np.einsum('ij,j->i',A,x)) #matrix-vector multiplication

[23 53 83]


In [81]:
# matrix multiplication
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print(np.einsum('ij,jk->ik',A,B))

[[19 22]
 [43 50]]


In [91]:
# trace of a matrix
A = np.array([[1,4],[3,5]])
print(np.einsum('ii->',A)) #diagonal value

6


In [89]:
# diagonal extraction
A = np.array([[1,4],[3,5]])
print(np.einsum('ii->i',A)) #diagonal value

[1 5]


## array printing options

In [93]:
# show floats with two decimal values
np.set_printoptions(precision=2)
a = np.array([12.23456,32.34535])
print(a)

[12.23 32.35]


In [97]:
# printing array to its max
np.set_printoptions(threshold=np.inf)

In [99]:
# increase the no of elements in a line
np.set_printoptions(linewidth=100)

In [100]:
a = np.array([[1,2,3],[3,4,5],[5,6,7]])
b = np.array([[2,3,4],[5,6,7],[8,9,1]])

In [101]:
a

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [102]:
b

array([[2, 3, 4],
       [5, 6, 7],
       [8, 9, 1]])

In [103]:
print(np.einsum('ii,ii->i',a,b))

[ 2 24  7]


In [104]:
a = np.array([[1,2],[3,4]])
print(np.einsum('ii->',a))

5


## linspace

In [108]:
np.linspace(10,101,10)  

array([ 10.  ,  20.11,  30.22,  40.33,  50.44,  60.56,  70.67,  80.78,  90.89, 101.  ])

## roadcasting

## boardcasting